# Generated by Django 4.2.6 on 2023-11-01 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppAssignment', '0002_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='first_nmme',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='last_nmme',
            new_name='last_name',
        ),
    ]
